#1
ClickerOfThings/OverpassLibrary pull request #1
Opened 2022-07-13 11:28 UTC by ClickerOfThings

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassClasses.cs
> +    public class osmClass
Название класса с большой буквы

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                osmClass newObj = new osmClass();
абстракция. Именуй экземпляры классов понятно

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +            foreach (dynamic city in mainObj)
переменные mainObj и newObj - плохо

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                newObj.CityId = city.osm_id;
зачем тебе CityId

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +        public static List<osmClass> GetAllPlacesInCity(osmClass cityInfo, params string[] placeTypes)
первый метод вызывает второй, не вижу смысла во втором методе.

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                $"&t={cityInfo.CityNorthEast.X}&r={cityInfo.CityNorthEast.Y}" +
Уточни можно ли указать версию API

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                if (i < placeTypes.Length - 1)
сделай через linq

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassClasses.cs
> +        public long Id { get; set; } = -1;
лишнее усложнение.

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassClasses.cs
> +        public string CityId { get; set; }
лишнее поле

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                    ObjType = osmClass.CharToObjType[placeObj.osm_id.Value.ToUpper()[0]],
Точно это нужно?

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                for (; objectCounter < currentMax; objectCounter++)
?

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                int currentMax = Math.Clamp(objectCounter + 50, int.MinValue, objectsToLookUp.Count);
вынеси в константу, чтобы было понятно

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                            objectsToLookUp[objectCounter].FullAddress);
рефакторинг

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassMethods.cs
> +                throw new ArgumentException("Пустой ответ от API. Вероятнее всего, неправильный ID или " +
мертвый код

2022-07-14 07:53 UTC, Armanitos94 commented on OverpassClasses.cs
> +            !string.IsNullOrEmpty(HouseNum);
сделай как поле

2022-07-15 04:59 UTC, ClickerOfThings commented on OverpassMethods.cs
> +                $"&t={cityInfo.CityNorthEast.X}&r={cityInfo.CityNorthEast.Y}" +
Нельзя, у Nominatim API нет возможности указывать версию

2022-07-15 07:17 UTC, Armanitos94 requested changes

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +            /*if (foundCities.Count == 0)
мертвый код

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +                return foundCities;
?

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +        /// Найти все OSM точки в прямоугольнике из базы данных openstreetmap.ru
объекты/места

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +        const int MAX_IDS_PER_POSTCODE_REQUEST = 50;
выше описать MаxIdsPerPostcodeRequest

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +        /// <exception cref="ArgumentException"></exception>
не описал

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +                for (; currentIndex < currentEndIndex; currentIndex++)
while

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +            for (int currentIndex = 0; currentIndex < objectsToLookUp.Count;)
while

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +                    requestUrlBuilder.Append(objectsToLookUp[currentIndex].OsmId);
упростить

2022-07-15 07:17 UTC, Armanitos94 commented on OverpassMethods.cs
> +                List<OsmClass> parsedObjsWithPostcodesFound = new List<OsmClass>(50);
ставь значение MаxIdsPerPostcodeRequest

2022-07-15 08:03 UTC, ClickerOfThings commented on OverpassMethods.cs
> +                return foundCities;
Теперь возвращаются null

2022-07-15 08:03 UTC, ClickerOfThings commented on OverpassMethods.cs
> +        /// Найти все OSM точки в прямоугольнике из базы данных openstreetmap.ru
Пока решено "места"

2022-07-15 08:03 UTC, ClickerOfThings commented on OverpassMethods.cs
> +        /// <exception cref="ArgumentException"></exception>
Снёс все ArgumentException-ы, заменил их возвратами null

2022-07-15 08:04 UTC, ClickerOfThings commented on OverpassMethods.cs
> +                for (; currentIndex < currentEndIndex; currentIndex++)
Реворк

2022-07-15 08:04 UTC, ClickerOfThings commented on OverpassMethods.cs
> +            for (int currentIndex = 0; currentIndex < objectsToLookUp.Count;)
Реворк

2022-07-15 08:04 UTC, ClickerOfThings commented on OverpassMethods.cs
> +                    requestUrlBuilder.Append(objectsToLookUp[currentIndex].OsmId);
string.Join

2022-07-15 08:59 UTC, Armanitos94 requested changes

2022-07-15 08:59 UTC, Armanitos94 commented on OverpassMethods.cs
> +                            OsmId = newOsmId,
сразу присвой

2022-07-20 07:11 UTC, Armanitos94 commented on OverpassMethods.cs
> +            for (int i = 0; i <= placesToLookUp.Count / MAX_IDS_PER_POSTCODE_REQUEST; i++)
потенциально ошибка

2022-07-20 07:11 UTC, Armanitos94 commented on OverpassMethods.cs
> +                            // - - - - - - - - - - поэтому приходится совмещать их вручную
не надо так делать

2022-07-20 07:11 UTC, Armanitos94 commented on OverpassMethods.cs
> +                IEnumerable<string> idsOfCurrentObjsRange =
CurrentPlacesRangeIds

2022-07-20 11:04 UTC, Armanitos94 approved these changes

2022-07-20 11:04 UTC, merged